import type { ReactElement } from 'react'
import Head from 'next/head'

// src
import ChartPage from '../src/components/pages/ChartPage'
import MainLayout from '../src/components/templates/MainLayout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Recharts test app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ChartPage />
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <MainLayout>{page}</MainLayout>
  )
}
